begin;

insert into public.ir_clients (
  id,
  nome,
  cpf_cnpj,
  responsavel_ir,
  vencimento,
  valor_servico,
  status_pagamento,
  status_declaracao,
  observacoes,
  created_at,
  updated_at
)
values
(gen_random_uuid(), 'ADOLFO DA COSTA ROSA', '58691936215', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ADRIANO JOSE CARNEIRO', '80321925149', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ALEXANDRA DE SOUSA DIAS FERNANDES', '4353088157', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ALEXANDRE RODRIGUES PIMENTEL', '2579511130', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ALINE DE SOUSA BRITO', '161945198', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ALINE DIAS MARTINS', '4074725177', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'AMELIA COSTA ARAUJO FRANCO', '14764830191', 'EDER GOMES FLEURY', null, 190, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ANA MARCIA ALVES DA SILVA RIBEIRO', '50845969153', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ANA PAULA CUNHA PONCE AMARAL', '99620456149', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ANA PAULA DE MORAES', '70176968164', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ANA PAULA NUNES DA SILVA MARINELLI', '136466133', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ANDERSON AFONSO DE FARIA', '84226811100', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ANDERSON ALEX AURELIANO', '88027503191', 'EDER GOMES FLEURY', null, 140, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ANDERSON AVOZANI SCHEMBERG', '4422132121', 'EDER GOMES FLEURY', null, 450, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ANDRE GARCIA TOMAZ', '1428184104', 'EDER GOMES FLEURY', null, 350, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ANDRE THIAGO DE ALMEIDA BARZ', '1613676158', 'ESCRITORIO', null, 400, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ANDREIA BARBALHA DE SOUSA DE CARVALHO', '5108752385', 'EDER GOMES FLEURY', null, 80, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ANICQUERSON AFONSO RESENDE', '50718606191', 'EDER GOMES FLEURY', null, 270, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ANTONIO CELSO FERREIRA FONSECA', '348120168', 'EDER GOMES FLEURY', null, 400, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ANTONIO EDUARDO GOMES FERNANDEZ', '36263740841', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ANTONIO FERREIRA DA SILVA', '45602220100', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ANTONIO HENRIQUE PEREIRA DE MACEDO', '6004385115', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ARLEIA RODRIGUES DE OLIVEIRA', '83368302191', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ARTHUR REIS BASTOS', '86416448149', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'BENTO BANDEIRA', '16835166134', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'BRUNA CUNHA DE MELLO', '75628457191', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'BRUNO GODOY RODRIGUES', '5498172630', 'EDER GOMES FLEURY', null, 300, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'CAMILA EVANGELISTA DE ANDRADE', '92395104191', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'CAMILLA CASSIANO A F ALVES', '474467147', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'CARLA BEATRIZ VIEIRA BATISTA AMARAL', '97560499104', 'EDER GOMES FLEURY', null, 300, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'CARLOS EDUARDO ASCOLI SILVA', '32403194115', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'CLARA MOREIRA LIMA', '785110119', 'EDER GOMES FLEURY', null, 80, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'CLEOMAR RODRIGUES ALVARENGA', '2335478192', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'CRISTIANE DE SOUZA SENA AURELIANO', '71110704100', 'EDER GOMES FLEURY', null, 80, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'CRISTIANE RODRIGUES LEMES', '94858551172', 'EDER GOMES FLEURY', null, 70, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'DANIEL FERREIRA DA SILVA', '42752566115', 'EDER GOMES FLEURY', null, 260, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'DANIEL WESLLEY SILVA DOS SANTOS', '1203025270', 'EDER GOMES FLEURY', null, 170, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'DANIELLY ARANHA SOARES', '71200550110', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'DANILO FLAVIO MACEDO MENEZES', '1088604188', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'DANILZA BISPO NEVES LUDOVIDO CURADO', '2276912103', 'EDER GOMES FLEURY', null, 170, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'DARCI DE MORAIS CARREIRA', '24674559120', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'DARIO MARTINS FERREIRA', '315850191', 'EDER GOMES FLEURY', null, 50, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'DENISE DE LIMA RAMOS', '92548474100', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'DIOGENES ROSA DE FREITAS JUNIOR', '3706439174', 'EDER GOMES FLEURY', null, 300, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'DIOGO DE SOUZA FREITAS', '3074116722', 'EDER GOMES FLEURY', null, 230, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'DOLORES FRIAS LIMA', '51726750191', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'DOUGLAS ALBINO MAGALHAES RABELO', '90317734172', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'EDER GOMES FLEURY', '86873598100', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'EDIMAR RUELA DA SILVA', '76733980100', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'EDUARDO GABRIEL GRAZZIOTIN', '5469265170', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ELAINY APARECIDA DA LUZ PONCIANO', '98887670110', 'EDER GOMES FLEURY', null, 120, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ELIENE LOPES MARTINS', '38295504134', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ELISA DANIELE ROSA', '85166502191', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ELISABETE VIEIRA DE MEDEIROS MACHADO', '58716238168', 'EDER GOMES FLEURY', null, 170, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ELISANDRO DA CUNHA SOUSA', '77674936104', 'EDER GOMES FLEURY', null, 350, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ELVIS BRUNO SIQUEIRA SANTOS', '88036383187', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'EMANOEL ALVES DA SILVEIRA', '87093693172', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'EMMANUELLE ALKMIM DE CASTRO BRANCO', '70069210152', 'VIVIAN', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ESCARLETE ALVES DE VASCONCELOS', '39561349825', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'EULER DA COSTA RAMOS', '82765715149', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'EVELYNE ARAUJO FRANCO', '80781756120', 'EDER GOMES FLEURY', null, 190, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'FABIANO MOREIRA REIS', '1893601196', 'EDER GOMES FLEURY', null, 300, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'FABIO GARCIA CARREIRA', '89975995187', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'FABRICIO GARCIA PRICIOTTI', '3965257684', 'EDER GOMES FLEURY', null, 190, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'FAUSTO LOPES TRINDADE', '21365369153', 'EDER GOMES FLEURY', null, 500, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'FELIPE AUGUSTO GASTALDON RIOS', '4091654177', 'VIVIAN', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'FERNANDO DA COSTA JUNQUEIRA', '75677113115', 'ESCRITORIO', null, 1200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'FLAVIA VIVIANE RODRIGUES DE SALES', '81616660163', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'GABRIEL CUNHA DE MELLO', '2983358160', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'GABRIEL FRANCO DE CASTRO', '999252143', 'EDER GOMES FLEURY', null, 270, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'GABRIEL VIEIRA GONÇALVES GONZAGA', '70418529116', 'EDER GOMES FLEURY', null, 120, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'GEOVANA EVANGELISTA DE FREITAS', '75049201187', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'GILBERT MACEDO LOBO', '59269855287', 'EDER GOMES FLEURY', null, 300, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'GILBERTO GOMES FREIRE', '50953427153', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'GILDA DA MOTA BASTOS', '47745126134', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'GILSON GERALDO VALERIO DO AMARAL', '80981348149', 'EDER GOMES FLEURY', null, 350, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'GRAZIELLE SANTOS FERRO PIRES SCHEMBERG', '70763097187', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'GUILHERME AFONSO DOS ANJOS RESENDE', '70575044110', 'EDER GOMES FLEURY', null, 120, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'GUILHERME WELINGTON BORGES DE LIMA', '331896176', 'EDER GOMES FLEURY', null, 280, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'GUSTAVO GODOY RODRIGUES', '7963794678', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'HALESON VIEIRA DA SILVA', '75306875149', 'ESCRITORIO', null, 300, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'HELIO PEREIRA BARRETO JUNIOR', '85822680178', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'HENE SAUD ANTURIANO', '781710162', 'EDER GOMES FLEURY', null, 400, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'HUGO MADALENA MOTTA', '6363142199', 'VIVIAN', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JACILENE MARIA DOS ANJOS RESENDE', '79474047120', 'EDER GOMES FLEURY', null, 120, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JADSON DOMINGOS DA CRUZ SILVA', '73283380', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JAFE TORRES JUNIOR', '53282485115', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JAIME APARECIDO GOMES FREIRE', '28834526104', 'EDER GOMES FLEURY', null, 60, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JAMIL DE SENA NUNES JUNIOR', '36670979134', 'EDER GOMES FLEURY', null, 300, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JANINE OLIVEIRA DE PAULA', '77731123120', 'EDER GOMES FLEURY', null, 300, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JOAO FRANCISCO REBOCHO NANITAS', '73141348120', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JOAO PAULO DOS SANTOS', '47763590572', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JOAO PAULO PROTASIO MUSSE', '3736095155', 'EDER GOMES FLEURY', null, 350, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JOAO PEDRO GUANAES FERREIRA', '75109409153', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JOSE AELCO GOMES PARREIRA', '63331870110', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JOSE WILLIAM CARNEIRO DE OLIVEIRA', '79947735168', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JOSILENE RODRIGUES SANTOS', '1104906147', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JULIANA CRISTINA COSTA DE SOUZA', '3152410123', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JULIO CESAR ALVES SOUZA', '95812920125', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JUSSARA COSTA DE SOUZA PINA', '64632130125', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'KENNYA CHRISTIANY CAVALCANTE LEIGUE', '46886117220', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LAIDISLAINE CAETANO FERREIRA SILVEIRA', '97241792149', 'EDER GOMES FLEURY', null, 120, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LAIZA LEITE ANTONELLI', '3746247128', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LANDIA MARIA LOURENCO WATANABE', '19112963100', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LARA CAROLINE SOARES FREITAS', '1940435170', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LARISSA DE PAIVA DAHER ROMANO FRANCA', '87262517104', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LARISSA GRACIELLI FRANCO DE FREITAS', '99802716120', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LELIA DE FATIMA BRUNO SENA', '85451177104', 'EDER GOMES FLEURY', null, 400, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LENIA MARIA ARANHA DE MACEDO', '3733165187', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LEONARDO DA SILVA PIRES', '79169406120', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LEONARDO DAVID AMARAL', '64889556168', 'EDER GOMES FLEURY', null, 1300, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LEONARDO RIBEIRO MONTEIRO BELEM', '81559704187', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LEONARDO RODRIGUES GARCIA', '4330472678', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LETICIA BOCKI TRISTAO ALVARENGA', '2688517198', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LORENA VALLENTINI ROSSI', '7122779190', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LUANNA PEREIRA SILVA', '2070106179', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LUCAS ANTONIO DE MORAIS GOMES', '87380145134', 'EDER GOMES FLEURY', null, 400, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LUCAS GABRIEL FERREIRA DE ALEXANDRIA', '4031033630', 'EDER GOMES FLEURY', null, 300, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LUCIA MARIA ARANHA SOARES', '9357424172', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LUCIANA DUARTE MOREIRA', '64977323300', 'EDER GOMES FLEURY', null, 170, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LUIS PHERNANDO MARINELLI', '7066050126', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LUIZ FERNANDO SANTOS DE OLIVEIRA', '2682768113', 'EDER GOMES FLEURY', null, 120, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LUIZ HENRIQUE FERNANDES SILVA', '2667868129', 'LUIZ', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LUIZA MARILLAC SENA', '24315494100', 'EDER GOMES FLEURY', null, 80, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LYW KONDRATIEVA NAZARETH BORGES', '93552335153', 'EDER GOMES FLEURY', null, 120, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MAFALDA PAZ ESTEVES FERREIRA FONSECA', '5831482120', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MAGDA DE SOUZA FERREIRA', '3122161141', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MAIKOW MARTHIELLO DHUNIOR FERNANDES DA SILVA BORGES', '3336311101', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MANOEL SEVERINO DE LUNA', '10400621134', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MARA LOULI MESQUITA', '87530627104', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MARCELO COZAC MOURA', '4649519179', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MARCIO CLAUDIO ROSA', '87822970100', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MARCIO DAVID RODRIGUES DA SILVA', '70378383140', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MARCUS VINICIUS RODRIGUES DE OLIVEIRA', '94465649134', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MARIA CRISTINA DE SOUZA LEMOS MONTEIRO', '56543646187', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MARIA EUNICE DOS SANTOS', '79618065634', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MARIA GONCALVES VIEIRA AFONSO', '80086160168', 'EDER GOMES FLEURY', null, 120, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MARIA LUIZA TREZZE PINHEIRO', '48628557172', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MARIA REGINA DA SILVA', '476256194', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MARIANICE JOSE RIBEIRO DOS REIS', '63349620191', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MARLUCIA DE SOUSA RODRIGUES', '86425137134', 'EDER GOMES FLEURY', null, 80, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MATHEUS FILIPE PEREIRA DOS SANTOS', '70485965119', 'EDER GOMES FLEURY', null, 80, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MATHEUS MOREIRA LIMA', '3328047123', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MAX HENRIQUE ARANHA DE MACEDO', '71187022187', 'EDER GOMES FLEURY', null, 170, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MAX JANNEDES OLIVEIRA SANTIAGO', '96728299149', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MICHELLI MIGUEL DE FREITAS', '298744163', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MILENA BASTOS CISNEIRO ROCHA', '95602607153', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MOZART SILVA ROCHA', '86397338134', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MURILO MARTINS HANNUM', '75644800172', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'NANCY ESPERANCA LOPES', '7130228172', 'EDER GOMES FLEURY', null, 600, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'NELCI PEREIRA FERREIRA', '8303789104', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'NELSON ANTONIO MARINELLI', '89229193100', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'NILTON RODRIGUES DE CARVALHO', '85721557168', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'NIVALDO DAVID FERREIRA FILHO', '4018856156', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'NIVALDO SEVERINO CUNHA', '11749199149', 'EDER GOMES FLEURY', null, 1000, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'OLVAIR MACHADO', '14345269172', 'EDER GOMES FLEURY', null, 350, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'OSVALDO MACHADO', '12346055115', 'EDER GOMES FLEURY', null, 400, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'PATRICIA LUCAS DOS SANTOS', '95607072134', 'EDER GOMES FLEURY', null, 220, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'PAULO JOSE FLEURY DO NASCIMENTO', '88292304134', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'PAULO OTAVIO DE SOUZA ALMEIDA', '6354621179', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'PAULO ROBERTO DA SILVA', '63112256115', 'VIVIAN', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'PAULO SERGIO HERNANDO', '72788160178', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'PAULO SERGIO RIBEIRO DA SILVA', '61125105', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'PEDRO AUGUSTO GONTIJO RAMOS', '3692017103', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'PHAUER JUNIO EUGENIO GONCALVES', '837185165', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'PRISCILLA PAZ ESTEVES FERREIRA FONSECA', '85618250144', 'EDER GOMES FLEURY', null, 600, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RAFAEL DE ALMEIDA BARZ', '93187122', 'ESCRITORIO', null, 300, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RAFAEL GIL SILVANO', '36717414812', 'EDER GOMES FLEURY', null, 700, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RAFAEL VILELA CAMPOS', '926301110', 'VIVIAN', null, 500, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RAIMUNDO FRANCISCO DA SILVA', '55673023120', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RAIZA RABELO MIGUEL', '2895704171', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RAPHAEL PIRES PONCIANO', '95837485104', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'REGINA CELIA DOS SANTOS PIRES', '40973018100', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RELPHLA GRACIELLE FREITAS BARBOSA SANTOS', '1138063100', 'EDER GOMES FLEURY', null, 120, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RENATO PEREIRA DE JESUS', '781579511', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RENATO RODRIGUES PIMENTEL', '99787652120', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RENZO BELIZARIO DE FREITAS', '81352441187', 'EDER GOMES FLEURY', null, 500, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RIVANILDO RODRIGUES DOS SANTOS', '1234124122', 'EDER GOMES FLEURY', null, 60, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ROBERTO CESAR LOPES FAIOLLA', '4389945157', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ROBERTO MOREIRA DOS SANTOS', '7367161733', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RODRIGO GUIMARAES TEIXEIRA', '2254894145', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RODRIGO MEDEIROS DE ALMEIDA LIMA', '59684682115', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RODRIGO SANTOS REZENDE', '5030760660', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ROGERIO TRISTAO', '32388748100', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RONIEL JUSTINO DE FREITAS', '589048163', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ROSANE LUCY LOPES FAIOLLA', '26263432187', 'EDER GOMES FLEURY', null, 350, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RUI BANDEIRA', '27842819149', 'EDER GOMES FLEURY', null, 220, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'SAMUEL DE SOUZA CALVAO', '35473860125', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'SAMUEL FERREIRA DA SILVA', '79807151104', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'SETUO WATANABE', '6095046149', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'SETUO WATANABE JUNIOR', '70613400100', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'SILVANA EVANGELISTA DE SOUSA', '83292861187', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'SILVIA ALVES DE SOUSA', '59880805100', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'SILVINO CARLOS BORGES', '21599122120', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'SILVIO AFONSO', '33573360149', 'EDER GOMES FLEURY', null, 120, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'SOFIA SANTIAGO HAONAT MACEDO', '3952842109', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'SONIA APARECIA DE OLIVEIRA', '56713487149', 'EDER GOMES FLEURY', null, 432, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'SUEIDY DOS SANTOS BARBOSA DA SILVA PIRES', '504113143', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'SUSANA CARMOSITA FALCAO TORRES', '69627460168', 'EDER GOMES FLEURY', null, 300, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'TACITO AUGUSTO RODRIGUES DE FREITAS', '57727872172', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'TAGORE ROBERT DO AMARAL FILHO', '74195352134', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'TAICY MARQUES DA SILVA', '1475774117', 'EDER GOMES FLEURY', null, 120, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'TANIA MARIA ALVES MARTINS REBOCHO NANITAS', '25583760125', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'TEREZINHA DANTAS DE SOUSA', '69091200197', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'THYALLITA RIBEIRO DE SOUZA', '3074505206', 'EDER GOMES FLEURY', null, 170, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'VALERIA CRISTIANE MARQUES DO NASCIMENTO', '10603489850', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'VALTER GERALDO DO PRADO', '83921150159', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'VALTER SOARES DOS SANTOS', '59941219168', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'VANCICLEIA ALVES SIMÕES', '94097330306', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'VANELY INACIO ABADIA', '62166212115', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'VERONILDE COELHO DE SOUZA FERREIRA', '30313198187', 'EDER GOMES FLEURY', null, 300, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'VIRGINIA DE OLIVEIRA SANTIAGO MACEDO', '69439850191', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'VITOR XAVIER DE OLIVEIRA NETO', '1207759139', 'VIVIAN', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'VIVIAN NASCIMENTO RIBEIRO', '1315681161', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'WALERIA CHRYSTINA ARTIAGA PROCOPIO', '69921679104', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'WALTERMIR XAVIER DE SOUSA', '13131265191', 'EDER GOMES FLEURY', null, 70, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'WASHINGTON LUIZ COSTA', '36074403104', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'WENDERLEY MARCELO DE SOUZA', '92183379120', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'WILDE SILVA DE PAULA', '92604234653', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'WILKER SILVA DE PAULA', '92606610644', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'WILLIAN COSTA DA SILVA', '9503673623', 'VIVIAN', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'EDI MARIA DA SILVA', '1108667112', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MARIA CLARA GODINHO PEREIRA BURITISAL', '2304559131', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'VICTORIA DIAS CARLOS DOS SANTOS', '70423994123', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'FRANCISCO RODRIGUES DA SILVA FILHO', '82316023134', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JOVEN RODRIGUES DE SOUZA JUNIOR', '69737657187', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RAFAELA DOMINGOS NASCIMENTO SOUZA', '93287607120', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'VINICIUS DA SILVA OLIVEIRA', '45129400810', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'SANDRIELLE DE SOUSA LOPES COSTA', '96952539115', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'KEANE CINTRA SOUSA PIRES', '1753784107', 'EDER GOMES FLEURY', null, 70, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'CAMILA GONÇALVES ALVES', '3021946143', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'BRUNO MAMEDE DE QUEIROZ', '70108482111', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LINDOMAR APRIGIO DIAS', '77736834172', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LORRANA DA SILVA PEREIRA', '70021408173', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'REGIANE ROSA DE CASTRO', '2513137', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ROGERIO CARDOSO DE CASTRO', '70161602118', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'DONIZETH QUEIROZ DA SILVA', '37515225149', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RAHNIX MAMEDE SOARES QUEIROZ', '1532791178', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JESSICA HELLENA CANDINE GRAZZIOTIN', '3874555151', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'SILVIO AFONSO JUNIOR', '2331968110', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'CARLOS MARTINS DOS SANTOS', '83721118120', 'EDER GOMES FLEURY', null, 0, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MUCIO HENRIQUE NASCIMENTO', '70175753180', 'EDER GOMES FLEURY', null, 300, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LEONARDO CARVALHO DE OLIVEIRA', '5880520609', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'JOSEANE RODRIGUES FERREIRA', '96906090178', 'EDER GOMES FLEURY', null, 300, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'ADHEMAR AUGUSTO VIEIRA MEDEIROS', '70387884181', 'EDER GOMES FLEURY', null, 500, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'LORENA BASTOS DE OLIVEIRA', '71438068115', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RAIELLY TOME MOURA', '70243730160', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'FABIA PEREIRA DE SÁ', '87772598172', 'EDER GOMES FLEURY', null, 150, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'NATAL PEREIRA DOS SANTOS', '46779949191', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MARCIA PIRES DA SILVA', '56539070144', 'EDER GOMES FLEURY', null, 250, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'RONIVALDO COUTINHO DOS SANTOS', '98231995153', 'EDER GOMES FLEURY', null, 200, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'MARIA DO SOCORRO DA COSTA RAMOS', '81456409115', 'EDER GOMES FLEURY', null, 100, 'A PAGAR', 'Pendente', null, now(), now()),
(gen_random_uuid(), 'WELLINGTON MARTINS DE SOUZA', '16916851443', 'EDER GOMES FLEURY', null, 300, 'A PAGAR', 'Pendente', null, now(), now());

commit;
